window.OIN_INITIAL_DATA = [
  {
    "ticket": "158",
    "task": "#158_Proyecto_Resultados",
    "description": "De acuerdo a la necesidad desde la Gerencia de juegos digitales se requiere iniciar con la arquitectura de contenido y estructura del proyecto de Sitio de Resultados, bajo la lógica y consumo de Datos de resultados en línea para todo usuario digital que requiera consultar vía Web(desktop/mobile)",
    "area": "Proyecto Resultados",
    "requestType": "Formulario Movilidad",
    "owner": "Juan David Monroy Machado",
    "manager": "Daniela Bermudez Infante",
    "priority": "Media",
    "bucket": "Haciendo",
    "rawStatus": "Pendiente",
    "status": "En curso",
    "progress": 50,
    "dueDate": "",
    "dueState": "Sin fecha",
    "meetingEligible": true
  },
  {
    "ticket": "159",
    "task": "#159_Revisión Baloto Crack_Tablero_Comercial",
    "description": "Revisión de cifras de fracciones de baloto crack",
    "area": "Comercial",
    "requestType": "Tablero",
    "owner": "Jessica Viviana Melo Parra",
    "manager": "Maria Nicole Vargas Gonzalez",
    "priority": "Media",
    "bucket": "Demoras",
    "rawStatus": "Pendiente",
    "status": "Vencido",
    "progress": 50,
    "dueDate": "2026-08-29 05:00:00",
    "dueState": "Vencida",
    "meetingEligible": true
  },
  {
    "ticket": "160",
    "task": "#160_Tablero venta por hora loterías_Tablero_Comercial",
    "description": "Se requiere revisar en tiempo real la venta por loterías.",
    "area": "Comercial",
    "requestType": "Tablero",
    "owner": "Maria Nicole Vargas Gonzalez",
    "manager": "Maria Nicole Vargas Gonzalez",
    "priority": "Media",
    "bucket": "Qué hacer",
    "rawStatus": "En progreso",
    "status": "Vencido",
    "progress": 50,
    "dueDate": "2026-08-21 05:00:00",
    "dueState": "Vencida",
    "meetingEligible": true
  },
  {
    "ticket": "161",
    "task": "#161_Plataforma Encuestas_Otro_Mercadeo",
    "description": "Se requiere de una plataforma que permita cargar formularios y recopilar toda la data, con opción de unica respuesta.",
    "area": "Mercadeo",
    "requestType": "Automatización",
    "owner": "Jessica Viviana Melo Parra",
    "manager": "Juan David Monroy Machado",
    "priority": "Media",
    "bucket": "Haciendo",
    "rawStatus": "Pendiente",
    "status": "En curso",
    "progress": 50,
    "dueDate": "2026-09-25 05:00:00",
    "dueState": "En plazo",
    "meetingEligible": true
  },
  {
    "ticket": "162",
    "task": "#162_RSE_y_Ambiental",
    "description": "Formulario de Sostenibilidad",
    "area": "RSE y Ambiental",
    "requestType": "Automatización",
    "owner": "Juan David Monroy Machado",
    "manager": "Juan David Monroy Machado",
    "priority": "Media",
    "bucket": "Haciendo",
    "rawStatus": "Pendiente",
    "status": "En curso",
    "progress": 50,
    "dueDate": "2026-11-30 05:00:00",
    "dueState": "En plazo",
    "meetingEligible": true
  },
  {
    "ticket": "163",
    "task": "#163_Comportamiento Ventas por Sismo_Otra_Comercial",
    "description": "Se requieren ver cifras de ventas después del sismo, para analizar repercusiones.",
    "area": "Comercial",
    "requestType": "Otra",
    "owner": "Asignación por corregir (3)",
    "manager": "Laura Vanessa Toro Escobar",
    "priority": "Media",
    "bucket": "Hecho",
    "rawStatus": "Completado en Planner",
    "status": "Hecho",
    "progress": 100,
    "dueDate": "2026-08-14 05:00:00",
    "dueState": "No aplica — completada",
    "meetingEligible": false
  },
  {
    "ticket": "164",
    "task": "#164_Análisis de venta de Dorado Noche_Otro_Comercial",
    "description": "Se requiere un análisis de venta de Dorado Noche y de la viabilidad de venderlo todos los días.",
    "area": "Comercial",
    "requestType": "Otra",
    "owner": "Asignación por corregir (3)",
    "manager": "Laura Vanessa Toro Escobar",
    "priority": "Media",
    "bucket": "Hecho",
    "rawStatus": "Completado en Planner",
    "status": "Hecho",
    "progress": 100,
    "dueDate": "2026-08-14 05:00:00",
    "dueState": "No aplica — completada",
    "meetingEligible": false
  },
  {
    "ticket": "165",
    "task": "#165_PESV",
    "description": "Diseño de formulario para Actualización de documentos del PESV",
    "area": "SST",
    "requestType": "Automatización",
    "owner": "Juan David Monroy Machado",
    "manager": "Juan David Monroy Machado",
    "priority": "Media",
    "bucket": "Haciendo",
    "rawStatus": "Pendiente",
    "status": "En curso",
    "progress": 50,
    "dueDate": "2026-09-11 05:00:00",
    "dueState": "En plazo",
    "meetingEligible": true
  },
  {
    "ticket": "166",
    "task": "#166_Rutero Recogedores_Movilidad_SST",
    "description": "Creación de rutero recogedores",
    "area": "SST",
    "requestType": "Automatización",
    "owner": "Asignación por corregir (2)",
    "manager": "Juan David Monroy Machado",
    "priority": "Media",
    "bucket": "Qué hacer",
    "rawStatus": "Pendiente",
    "status": "Vencido",
    "progress": 0,
    "dueDate": "2026-08-28 05:00:00",
    "dueState": "Vencida",
    "meetingEligible": true
  },
  {
    "ticket": "169",
    "task": "#169_Asignación Permisos Tableros_Soporte_Comercial",
    "description": "A partir de la fecha me encuentro en la SPT de Sur occidente OF realizando apoyo operativo a la directora @Leidy Viviana Barrantes Herrera en el periodo comprendido entre el 20 de agosto del 2026, finalización por definir, por este motivo solicito su colaboración para realizar el cambio correspondiente en los informes POWER BI, muchas gracias.",
    "area": "Comercial",
    "requestType": "Soporte",
    "owner": "Maria Nicole Vargas Gonzalez",
    "manager": "Laura Vanessa Toro Escobar",
    "priority": "Media",
    "bucket": "Hecho",
    "rawStatus": "Completado en Planner",
    "status": "Hecho",
    "progress": 100,
    "dueDate": "2026-08-25 05:00:00",
    "dueState": "No aplica — completada",
    "meetingEligible": false
  },
  {
    "ticket": "170",
    "task": "#170_Solucionar tableros Chance_Tablero_Mercadeo",
    "description": "Buen día, No está sirviendo tableros para la información de Chance.",
    "area": "Mercadeo",
    "requestType": "Tablero",
    "owner": "Laura Vanessa Toro Escobar",
    "manager": "Maria Nicole Vargas Gonzalez",
    "priority": "Media",
    "bucket": "Qué hacer",
    "rawStatus": "Pendiente",
    "status": "Vencido",
    "progress": 0,
    "dueDate": "2026-08-28 05:00:00",
    "dueState": "Vencida",
    "meetingEligible": true
  },
  {
    "ticket": "171",
    "task": "#171_Visita 10 ago Movilidad_Soporte_Comercial",
    "description": "Se solicita la validación de la visita del 10 de agosto que se encuentra duplicada en la App Movilidad y no muestra visit ID.",
    "area": "Comercial",
    "requestType": "Soporte",
    "owner": "Asignación por corregir (2)",
    "manager": "Laura Vanessa Toro Escobar",
    "priority": "Media",
    "bucket": "Hecho",
    "rawStatus": "Completado",
    "status": "Hecho",
    "progress": 100,
    "dueDate": "2026-08-24 05:00:00",
    "dueState": "No aplica — completada",
    "meetingEligible": false
  },
  {
    "ticket": "172",
    "task": "#172_Optimización licencias_Formulario Movilidad_OIN",
    "description": "Se requiere la validación del uso de la App Movilidad por parte de los técnicos de Datacenter.",
    "area": "OIN",
    "requestType": "Formulario Movilidad",
    "owner": "Asignación por corregir (2)",
    "manager": "Daniela Bermudez Infante",
    "priority": "Importante",
    "bucket": "Hecho",
    "rawStatus": "Completado",
    "status": "Hecho",
    "progress": 100,
    "dueDate": "2026-08-28 05:00:00",
    "dueState": "No aplica — completada",
    "meetingEligible": false
  },
  {
    "ticket": "173",
    "task": "#173_Consolidado Puntos Especializados_Movilidad_OIN",
    "description": "Generar la base de los especializados con el nombre del TAT más todos los atributos como zona, SPT, coordenadas y demás criterios que se necesiten para compartirle al Área de Analítica y Automatización",
    "area": "OIN",
    "requestType": "Formulario Movilidad",
    "owner": "Asignación por corregir (2)",
    "manager": "Daniela Bermudez Infante",
    "priority": "Media",
    "bucket": "Qué hacer",
    "rawStatus": "Pendiente",
    "status": "Vencido",
    "progress": 0,
    "dueDate": "2026-08-28 05:00:00",
    "dueState": "Vencida",
    "meetingEligible": true
  },
  {
    "ticket": "174",
    "task": "#174_Asignación de nombres a puntos Especializados_Movilidad_OIN",
    "description": "Realizar la asignación de los nombres de los TAT a los puntos especializados en Datarutas",
    "area": "OIN",
    "requestType": "Soporte",
    "owner": "Asignación por corregir (2)",
    "manager": "Laura Vanessa Toro Escobar",
    "priority": "Media",
    "bucket": "Qué hacer",
    "rawStatus": "Pendiente",
    "status": "Vencido",
    "progress": 0,
    "dueDate": "2026-08-28 05:00:00",
    "dueState": "Vencida",
    "meetingEligible": true
  },
  {
    "ticket": "175",
    "task": "#175_BEPS en el Form. Acompañamiento Colocadoras_Formulario Movilidad_Desarrollo Organizacional",
    "description": "Por favor incluir el tema de BEPS como recaudo en PDV dentro del formulario Acompañamientos Colocadoras de Apuestas.",
    "area": "OIN",
    "requestType": "Formulario Movilidad",
    "owner": "Asignación por corregir (3)",
    "manager": "Daniela Bermudez Infante",
    "priority": "Media",
    "bucket": "Haciendo",
    "rawStatus": "Pendiente",
    "status": "En curso",
    "progress": 50,
    "dueDate": "2026-09-04 05:00:00",
    "dueState": "En plazo",
    "meetingEligible": true
  },
  {
    "ticket": "176",
    "task": "#176_Bre-b, Sorteo Express Form. Acompañamiento Colocadoras_Formulario Movilidad_Desarrollo Organizacional",
    "description": "Buen día. Quisiera solicitar por favor la inclusión de dos nuevos productos en la aplicación de movilidad: Bre-b y sorteo express. Adicionalmente estaré enviando por correo el detalle de los temas y contenidos asociados para su respectiva revisión y gestión. Muchas gracias",
    "area": "Desarrollo organizacional",
    "requestType": "Formulario Movilidad",
    "owner": "Asignación por corregir (3)",
    "manager": "Daniela Bermudez Infante",
    "priority": "Media",
    "bucket": "Haciendo",
    "rawStatus": "Pendiente",
    "status": "En curso",
    "progress": 50,
    "dueDate": "2026-09-04 05:00:00",
    "dueState": "En plazo",
    "meetingEligible": true
  },
  {
    "ticket": "177",
    "task": "#177_Actualización grupo_Otra_Comercial",
    "description": "De manera atenta solicito retirar de los tableros de data rutas de Occidente Vd, a los administradores relacionados, quienes fueron trasladados a otra SPT. Gracias",
    "area": "Comercial",
    "requestType": "Soporte",
    "owner": "Asignación por corregir (2)",
    "manager": "Laura Vanessa Toro Escobar",
    "priority": "Media",
    "bucket": "Hecho",
    "rawStatus": "Completado en Planner",
    "status": "Hecho",
    "progress": 100,
    "dueDate": "2026-08-24 05:00:00",
    "dueState": "No aplica — completada",
    "meetingEligible": false
  },
  {
    "ticket": "178",
    "task": "#178_Habilitación tablero VISITAS COMERCIALES_Tablero_Comercial",
    "description": "Habilitacion tablero VISITAS COMERCIAL, esto con el objetivo de validar la gestion de Visitas en Campo de los tres administradores de KENO",
    "area": "Comercial",
    "requestType": "Tablero",
    "owner": "Laura Vanessa Toro Escobar",
    "manager": "Maria Nicole Vargas Gonzalez",
    "priority": "Media",
    "bucket": "Qué hacer",
    "rawStatus": "Pendiente",
    "status": "Vencido",
    "progress": 0,
    "dueDate": "2026-08-31 05:00:00",
    "dueState": "Vencida",
    "meetingEligible": true
  },
  {
    "ticket": "179",
    "task": "#179_ Actualización Apertura y cierre_Soporte_Comercial",
    "description": "Se solicita la validación del tablero Apertura y Cierre de puntos, ya que se actualizaron los horarios de los puntos pero aun no se visualizan.",
    "area": "Comercial",
    "requestType": "Tablero",
    "owner": "Maria Nicole Vargas Gonzalez",
    "manager": "Maria Nicole Vargas Gonzalez",
    "priority": "Media",
    "bucket": "Hecho",
    "rawStatus": "Completado en Planner",
    "status": "Hecho",
    "progress": 100,
    "dueDate": "2026-08-24 05:00:00",
    "dueState": "No aplica — completada",
    "meetingEligible": false
  },
  {
    "ticket": "181",
    "task": "#181_Inactivación_Puntos (+1 más)",
    "description": "Se solicita la ejecución del proceso de inactivación masiva de los puntos en Datarutas.",
    "area": "OIN",
    "requestType": "Automatización",
    "owner": "Juan David Monroy Machado",
    "manager": "Juan David Monroy Machado",
    "priority": "Media",
    "bucket": "Hecho",
    "rawStatus": "Cerrado",
    "status": "Hecho",
    "progress": 100,
    "dueDate": "2026-08-28 05:00:00",
    "dueState": "No aplica — completada",
    "meetingEligible": false
  },
  {
    "ticket": "182",
    "task": "#182_Revisión presupuesto Girardot_Soporte_Comercial",
    "description": "Buen día equipo OIN, solicito amablemente se verifique los valores de presupuesto y venta en el informe de ventas por hora de Girardot, ya que no coincide con el que me envía comercial, Gracias",
    "area": "Comercial",
    "requestType": "Tablero",
    "owner": "Maria Nicole Vargas Gonzalez",
    "manager": "Maria Nicole Vargas Gonzalez",
    "priority": "Media",
    "bucket": "Qué hacer",
    "rawStatus": "En progreso",
    "status": "Vencido",
    "progress": 50,
    "dueDate": "2026-08-27 05:00:00",
    "dueState": "Vencida",
    "meetingEligible": true
  },
  {
    "ticket": "183",
    "task": "#183_Asignación Tablero Desarrollo Organizacional_Soporte_Comercial",
    "description": "Realizar validación de las visitas realizadas por las entrenadoras de la regional, gracias",
    "area": "comercial",
    "requestType": "Tablero",
    "owner": "Maria Nicole Vargas Gonzalez",
    "manager": "Maria Nicole Vargas Gonzalez",
    "priority": "Media",
    "bucket": "Hecho",
    "rawStatus": "Completado en Planner",
    "status": "Hecho",
    "progress": 100,
    "dueDate": "2026-08-25 05:00:00",
    "dueState": "No aplica — completada",
    "meetingEligible": false
  },
  {
    "ticket": "184",
    "task": "#184_Prueba Actualización_Automatización_OIN",
    "description": "Prueba Actualización",
    "area": "oin",
    "requestType": "Automatización",
    "owner": "Laura Vanessa Toro Escobar",
    "manager": "Juan David Monroy Machado",
    "priority": "Media",
    "bucket": "Qué hacer",
    "rawStatus": "Pendiente",
    "status": "Vencido",
    "progress": 0,
    "dueDate": "2026-09-01 05:00:00",
    "dueState": "Vencida",
    "meetingEligible": true
  },
  {
    "ticket": "185",
    "task": "#185_Prueba_Automatización_OIN",
    "description": "Prueba",
    "area": "OIN",
    "requestType": "Automatización",
    "owner": "Laura Vanessa Toro Escobar",
    "manager": "Juan David Monroy Machado",
    "priority": "Media",
    "bucket": "Qué hacer",
    "rawStatus": "Pendiente",
    "status": "Vencido",
    "progress": 0,
    "dueDate": "2026-09-01 05:00:00",
    "dueState": "Vencida",
    "meetingEligible": true
  },
  {
    "ticket": "186",
    "task": "#186_Asignación Tablero Seguridad Vial_Tablero_SST",
    "description": "De manera atenta solicito la autorización de ingreso para seguimiento del tablero preoperacionales de recogedores",
    "area": "SST",
    "requestType": "Tablero",
    "owner": "Johan Santiago Tautiva Romero",
    "manager": "Maria Nicole Vargas Gonzalez",
    "priority": "Media",
    "bucket": "Hecho",
    "rawStatus": "Completado en Planner",
    "status": "Hecho",
    "progress": 100,
    "dueDate": "2026-08-27 05:00:00",
    "dueState": "No aplica — completada",
    "meetingEligible": false
  },
  {
    "ticket": "187",
    "task": "#187_Acceso solicitado_Soporte_Seguridad Física",
    "description": "Buenas tardes, se solicita el acceso al tablero de Recaudo Escoltas para el equipo de Monitoreo. Correos: edna.santiesteban@gelsa.com.co y andres.vasquez@gelsa.com.co",
    "area": "Seguridad Física",
    "requestType": "Soporte",
    "owner": "Johan Santiago Tautiva Romero",
    "manager": "Laura Vanessa Toro Escobar",
    "priority": "Media",
    "bucket": "Hecho",
    "rawStatus": "Cerrado",
    "status": "Hecho",
    "progress": 100,
    "dueDate": "2026-09-01 05:00:00",
    "dueState": "No aplica — completada",
    "meetingEligible": false
  },
  {
    "ticket": "188",
    "task": "#188_Permiso Tableros Digital_Soporte_Juegos Digitales",
    "description": "Solicito de su colaboración con acceso a raul.arango@gelsa.com.co a los tableros https://portalanalitica.gelsa.com.co/reports/179 https://portalanalitica.gelsa.com.co/reports/167 https://portalanalitica.gelsa.com.co/reports/103 https://portalanalitica.gelsa.com.co/reports/107 https://portalanalitica.gelsa.com.co/reports/201 esto con el fin de que el analista de medios pagos pueda mantener el seguimiento sobre negocios y tomar decisiones estrategicas que involucran su especialidad.",
    "area": "Gerencia Juegos Digitales",
    "requestType": "Tablero",
    "owner": "Maria Nicole Vargas Gonzalez",
    "manager": "Maria Nicole Vargas Gonzalez",
    "priority": "Media",
    "bucket": "Hecho",
    "rawStatus": "Completado en Planner",
    "status": "Hecho",
    "progress": 100,
    "dueDate": "2026-08-27 05:00:00",
    "dueState": "No aplica — completada",
    "meetingEligible": false
  },
  {
    "ticket": "189",
    "task": "#189_Actualización tablero solicitado_Tablero_Mercadeo",
    "description": "Buen día. Solicito se realicen los siguientes ajustes a la logica del tablero de RFM acorde a las siguientes observaciones: Recencia Frecuencia 1 6 meses o más 1 49 o menos tx 2 91 a 180 días 2 50 a 99 tx 3 61 a 90 días 3 100 a 249 tx 4 30 a 60 días 4 250 a 499 tx 5 16 a 30 dias 5 500 a 749 tx 6 8 a 15 dias 6 750 a 999 tx 7 1 a 7 días 7 1000 o mas tx Dias desde la ultima compra 12 meses",
    "area": "Mercadeo",
    "requestType": "Tablero",
    "owner": "Laura Vanessa Toro Escobar",
    "manager": "Maria Nicole Vargas Gonzalez",
    "priority": "Media",
    "bucket": "Qué hacer",
    "rawStatus": "Pendiente",
    "status": "Pendiente",
    "progress": 0,
    "dueDate": "2026-09-04 05:00:00",
    "dueState": "En plazo",
    "meetingEligible": true
  },
  {
    "ticket": "190",
    "task": "#190_Creación informe mensual de realización_Automatización_SST",
    "description": "Creación informe mensual de realización de preoperacionales por persona y SPT - Comunicación con Santiago",
    "area": "SST",
    "requestType": "Automatización",
    "owner": "Laura Vanessa Toro Escobar",
    "manager": "Juan David Monroy Machado",
    "priority": "Media",
    "bucket": "Qué hacer",
    "rawStatus": "Pendiente",
    "status": "Pendiente",
    "progress": 0,
    "dueDate": "2026-09-04 05:00:00",
    "dueState": "En plazo",
    "meetingEligible": true
  },
  {
    "ticket": "191",
    "task": "#191_Indisponibilidad Viewer_Soporte_Comercial",
    "description": "Buen día, Actual mente no me permite visualizar el rutero de visitas. Error; El relleno no es valido y no se puede eliminar.",
    "area": "COMERCIAL",
    "requestType": "Tablero",
    "owner": "Maria Nicole Vargas Gonzalez",
    "manager": "Maria Nicole Vargas Gonzalez",
    "priority": "Media",
    "bucket": "Hecho",
    "rawStatus": "Cerrado",
    "status": "Hecho",
    "progress": 100,
    "dueDate": "2026-09-02 05:00:00",
    "dueState": "No aplica — completada",
    "meetingEligible": false
  },
  {
    "ticket": "192",
    "task": "#192_Asignacion preoperacional_Movilidad_OIN",
    "description": "Realizar asignación de la actividad Inspección diaria vehicular correspondiente a los meses de septiembre y octubre",
    "area": "OIN",
    "requestType": "Otra",
    "owner": "Laura Vanessa Toro Escobar",
    "manager": "Laura Vanessa Toro Escobar",
    "priority": "Media",
    "bucket": "Hecho",
    "rawStatus": "Cerrado",
    "status": "Hecho",
    "progress": 100,
    "dueDate": "2026-09-01 05:00:00",
    "dueState": "No aplica — completada",
    "meetingEligible": false
  },
  {
    "ticket": "193",
    "task": "#193_Ajuste evaluación lider_Automatizacion_Desarrollo Organizacional",
    "description": "Juan solicitamos tu ayuda ajustando el power apps, para que solo quede disponible el botón de evaluación líder y obversiones",
    "area": "DESARROLLO ORGANIZACIONAL",
    "requestType": "Automatización",
    "owner": "Juan David Monroy Machado",
    "manager": "Juan David Monroy Machado",
    "priority": "Media",
    "bucket": "Hecho",
    "rawStatus": "Cerrado",
    "status": "Hecho",
    "progress": 100,
    "dueDate": "2026-09-04 05:00:00",
    "dueState": "No aplica - completada",
    "meetingEligible": false
  },
  {
    "ticket": "194",
    "task": "#194_Ajuste Tablero Referidos_Soporte_Mercadeo",
    "description": "En reporte fuerza de ventas incluir cuántas transacciones y venta tienen por código referido (Conservar la data actual) incluir filtro por producto, incluir también cantidad de usuarios a los cuales la asesora le asocio las compras al tipo y número de documento.",
    "area": "Mercadeo",
    "requestType": "Soporte",
    "owner": "Maria Nicole Vargas Gonzalez",
    "manager": "Laura Vanessa Toro Escobar",
    "priority": "Media",
    "bucket": "Hecho",
    "rawStatus": "Cerrado",
    "status": "Hecho",
    "progress": 100,
    "dueDate": "2026-09-02 05:00:00",
    "dueState": "No aplica — completada",
    "meetingEligible": false
  },
  {
    "ticket": "195",
    "task": "#195_Control Rollo a Destrucción_Automatización_Operaciones",
    "description": "Realizar una herramienta en donde el proceso de pistolear rollos para destrucción sea más fácil para la operatividad, además, identificar el informe que se debe tener para tener los rollos listos a destrucción",
    "area": "Operaciones",
    "requestType": "Automatización",
    "owner": "Johan Santiago Tautiva Romero",
    "manager": "Juan David Monroy Machado",
    "priority": "Media",
    "bucket": "Hecho",
    "rawStatus": "Cerrado",
    "status": "Hecho",
    "progress": 100,
    "dueDate": "",
    "dueState": "No aplica - completada",
    "meetingEligible": false
  },
  {
    "ticket": "196",
    "task": "#196_EPD para Paga Millonario_Otro_Innovacion",
    "description": "Creación simulador del EPD para Paga Millonario",
    "area": "Innovación",
    "requestType": "Automatización",
    "owner": "Juan Camilo Potosi Agudelo",
    "manager": "Juan David Monroy Machado",
    "priority": "Media",
    "bucket": "Hecho",
    "rawStatus": "Completado en Planner",
    "status": "Hecho",
    "progress": 100,
    "dueDate": "",
    "dueState": "No aplica — completada",
    "meetingEligible": false
  },
  {
    "ticket": "197",
    "task": "#197_Indicadores de calidad_Tablero_Operaciones",
    "description": "Validar y ajustar el indicador de calidad del tablero de Operaciones.",
    "area": "Operaciones",
    "requestType": "Tablero",
    "owner": "Maria Nicole Vargas Gonzalez",
    "manager": "Maria Nicole Vargas Gonzalez",
    "priority": "Media",
    "bucket": "Qué hacer",
    "rawStatus": "No iniciada",
    "status": "Pendiente",
    "progress": 0,
    "dueDate": "",
    "dueState": "Sin fecha",
    "meetingEligible": true
  },
  {
    "ticket": "198",
    "task": "#198_Creación de proveedores_Compras_Automatizacion",
    "description": "Automatizar la creación de proveedores.",
    "area": "Compras",
    "requestType": "Automatización",
    "owner": "Juan David Monroy Machado",
    "manager": "Juan David Monroy Machado",
    "priority": "Media",
    "bucket": "Qué hacer",
    "rawStatus": "No iniciada",
    "status": "Pendiente",
    "progress": 0,
    "dueDate": "",
    "dueState": "Sin fecha",
    "meetingEligible": true
  },
  {
    "ticket": "199",
    "task": "#199_Cargue presupuesto Rifas_Tablero_OIN",
    "description": "Cargue y actualización del presupuesto de Rifas.",
    "area": "OIN",
    "requestType": "Tablero",
    "owner": "Maria Nicole Vargas Gonzalez",
    "manager": "Maria Nicole Vargas Gonzalez",
    "priority": "Media",
    "bucket": "Hecho",
    "rawStatus": "Cerrado",
    "status": "Hecho",
    "progress": 100,
    "dueDate": "",
    "dueState": "No aplica - completada",
    "meetingEligible": false
  },
  {
    "ticket": "200",
    "task": "#200_Informe Junta directiva_Tablero_Comercial",
    "description": "Actualizar el informe para la Junta Directiva.",
    "area": "Comercial",
    "requestType": "Tablero",
    "owner": "Maria Nicole Vargas Gonzalez",
    "manager": "Maria Nicole Vargas Gonzalez",
    "priority": "Media",
    "bucket": "Haciendo",
    "rawStatus": "En progreso",
    "status": "En curso",
    "progress": 0,
    "dueDate": "2026-09-10 05:00:00",
    "dueState": "En plazo",
    "meetingEligible": true
  },
  {
    "ticket": "201",
    "task": "#201_Informe de ventas por loteria_Tablero_Comercial",
    "description": "Generar informe de ventas por lotería y municipio.",
    "area": "Comercial",
    "requestType": "Tablero",
    "owner": "Maria Nicole Vargas Gonzalez",
    "manager": "Maria Nicole Vargas Gonzalez",
    "priority": "Media",
    "bucket": "Haciendo",
    "rawStatus": "En progreso",
    "status": "En curso",
    "progress": 0,
    "dueDate": "2026-09-10 05:00:00",
    "dueState": "En plazo",
    "meetingEligible": true
  },
  {
    "ticket": "202",
    "task": "#202_Informe ingresos_Tablero_Comunicaciones",
    "description": "Actualizar el informe de ingresos de Comunicaciones.",
    "area": "Comunicaciones",
    "requestType": "Tablero",
    "owner": "Maria Nicole Vargas Gonzalez",
    "manager": "Maria Nicole Vargas Gonzalez",
    "priority": "Media",
    "bucket": "Haciendo",
    "rawStatus": "Completado en Planner",
    "status": "Hecho",
    "progress": 100,
    "dueDate": "2026-09-15 05:00:00",
    "dueState": "No aplica — completada",
    "meetingEligible": false
  },
  {
    "ticket": "203",
    "task": "#203_Logica de redondeo_Tablero_Financiera",
    "description": "Revisar la lógica de redondeo del tablero.",
    "area": "Financiera",
    "requestType": "Tablero",
    "owner": "Maria Nicole Vargas Gonzalez",
    "manager": "Maria Nicole Vargas Gonzalez",
    "priority": "Media",
    "bucket": "Hecho",
    "rawStatus": "Completado",
    "status": "Hecho",
    "progress": 100,
    "dueDate": "",
    "dueState": "No aplica — completada",
    "meetingEligible": false
  },
  {
    "ticket": "204",
    "task": "#204_Informes de derechos de explotacion_Tablero_Financiera",
    "description": "Generar informes de derechos de explotación.",
    "area": "Financiera",
    "requestType": "Tablero",
    "owner": "Maria Nicole Vargas Gonzalez",
    "manager": "Maria Nicole Vargas Gonzalez",
    "priority": "Media",
    "bucket": "Hecho",
    "rawStatus": "Completado en Planner",
    "status": "Hecho",
    "progress": 100,
    "dueDate": "",
    "dueState": "No aplica — completada",
    "meetingEligible": false
  },
  {
    "ticket": "205",
    "task": "#205_Formulario de calidad_Tablero_Calidad",
    "description": "Poner en producción el formulario de calidad.",
    "area": "Calidad",
    "requestType": "Tablero",
    "owner": "Juan David Monroy Machado",
    "manager": "Maria Nicole Vargas Gonzalez",
    "priority": "Media",
    "bucket": "Hecho",
    "rawStatus": "Cerrado",
    "status": "Hecho",
    "progress": 100,
    "dueDate": "",
    "dueState": "No aplica — completada",
    "meetingEligible": false
  },
  {
    "ticket": "206",
    "task": "#206_Informe administradores_Tablero_Comercial",
    "description": "Producir el informe de administradores.",
    "area": "Comercial",
    "requestType": "Tablero",
    "owner": "Maria Nicole Vargas Gonzalez",
    "manager": "Maria Nicole Vargas Gonzalez",
    "priority": "Media",
    "bucket": "Qué hacer",
    "rawStatus": "No iniciada",
    "status": "Pendiente",
    "progress": 0,
    "dueDate": "",
    "dueState": "Sin fecha",
    "meetingEligible": true
  },
  {
    "ticket": "207",
    "task": "#207_Detalle Giros estáticos_Tablero_Comercial",
    "description": "Generar el detalle de giros estáticos.",
    "area": "Comercial",
    "requestType": "Tablero",
    "owner": "Maria Nicole Vargas Gonzalez",
    "manager": "Maria Nicole Vargas Gonzalez",
    "priority": "Media",
    "bucket": "Qué hacer",
    "rawStatus": "No iniciada",
    "status": "Pendiente",
    "progress": 0,
    "dueDate": "",
    "dueState": "Sin fecha",
    "meetingEligible": true
  },
  {
    "ticket": "208",
    "task": "#208_Lógica de la ONJ Baloto y revancha_Tablero_Comercial",
    "description": "Validar la lógica de la ONJ para Baloto y Revancha.",
    "area": "Comercial",
    "requestType": "Tablero",
    "owner": "Maria Nicole Vargas Gonzalez",
    "manager": "Maria Nicole Vargas Gonzalez",
    "priority": "Media",
    "bucket": "Qué hacer",
    "rawStatus": "No iniciada",
    "status": "Pendiente",
    "progress": 0,
    "dueDate": "",
    "dueState": "Sin fecha",
    "meetingEligible": true
  },
  {
    "ticket": "209",
    "task": "#209_Correciones tablero pásarela_Tablero_Juegos Digitales",
    "description": "Validar y corregir el tablero de pasarela.",
    "area": "Juegos Digitales",
    "requestType": "Tablero",
    "owner": "Maria Nicole Vargas Gonzalez",
    "manager": "Maria Nicole Vargas Gonzalez",
    "priority": "Media",
    "bucket": "Hecho",
    "rawStatus": "Cerrado",
    "status": "Hecho",
    "progress": 100,
    "dueDate": "",
    "dueState": "No aplica — completada",
    "meetingEligible": false
  },
  {
    "ticket": "210",
    "task": "#210_Reporte Mensual Todopay_Tablero_Juegos Digitales",
    "description": "Generar el reporte mensual de TodoPay.",
    "area": "Juegos Digitales",
    "requestType": "Tablero",
    "owner": "Maria Nicole Vargas Gonzalez",
    "manager": "Maria Nicole Vargas Gonzalez",
    "priority": "Media",
    "bucket": "Qué hacer",
    "rawStatus": "No iniciada",
    "status": "Pendiente",
    "progress": 0,
    "dueDate": "",
    "dueState": "Sin fecha",
    "meetingEligible": true
  },
  {
    "ticket": "211",
    "task": "#211_Reporte Coljuegos Inventario tdv_Soporte_Comercial",
    "description": "Generar reporte de Coljuegos e inventario TDV.",
    "area": "Comercial",
    "requestType": "Tablero",
    "owner": "Maria Nicole Vargas Gonzalez",
    "manager": "Maria Nicole Vargas Gonzalez",
    "priority": "Media",
    "bucket": "Hecho",
    "rawStatus": "Completado en Planner",
    "status": "Hecho",
    "progress": 100,
    "dueDate": "",
    "dueState": "No aplica — completada",
    "meetingEligible": false
  },
  {
    "ticket": "213",
    "task": "#213_Ajuste Informe Chance Filtro por Vendedor_Soporte_Comercial",
    "description": "Dar acceso al filtro de canales en el tablero de Chance.",
    "area": "Mercadeo",
    "requestType": "Tablero",
    "owner": "Maria Nicole Vargas Gonzalez",
    "manager": "Maria Nicole Vargas Gonzalez",
    "priority": "Media",
    "bucket": "Hecho",
    "rawStatus": "Completado en Planner",
    "status": "Hecho",
    "progress": 100,
    "dueDate": "2026-09-03 05:00:00",
    "dueState": "No aplica — completada",
    "meetingEligible": false
  },
  {
    "ticket": "214",
    "task": "#214_Actualilzacion tablero_Automatizacion_Estrategia-calidad",
    "description": "Actualizar el tablero de Estrategia-Calidad.",
    "area": "Estrategia-Calidad",
    "requestType": "Automatización",
    "owner": "Juan David Monroy Machado",
    "manager": "Juan David Monroy Machado",
    "priority": "Media",
    "bucket": "Haciendo",
    "rawStatus": "En progreso",
    "status": "En curso",
    "progress": 0,
    "dueDate": "",
    "dueState": "Sin fecha",
    "meetingEligible": true
  },
  {
    "ticket": "215",
    "task": "#215_Ranking SPT Canal Digital_Soporte_Juegos Digitales",
    "description": "Ranking de ventas por SPT incluyendo oficina virtual y Canal Digital.",
    "area": "Juegos Digitales",
    "requestType": "Tablero",
    "owner": "Juan Camilo Potosi Agudelo",
    "manager": "Maria Nicole Vargas Gonzalez",
    "priority": "Media",
    "bucket": "Hecho",
    "rawStatus": "Cerrado",
    "status": "Hecho",
    "progress": 100,
    "dueDate": "2026-09-04 05:00:00",
    "dueState": "No aplica — completada",
    "meetingEligible": false
  },
  {
    "ticket": "216",
    "task": "#216_Actualización tabla de procesos y sincronización flujo n8n_Soporte_Calidad",
    "description": "Actualizar la tabla de procesos y sincronizar el flujo n8n; el formulario ya quedó funcionando.",
    "area": "Calidad",
    "requestType": "Soporte",
    "owner": "Juan Camilo Potosi Agudelo",
    "manager": "Laura Vanessa Toro Escobar",
    "priority": "Media",
    "bucket": "Hecho",
    "rawStatus": "Cerrado",
    "status": "Hecho",
    "progress": 100,
    "dueDate": "",
    "dueState": "No aplica — completada",
    "meetingEligible": false
  },
  {
    "ticket": "217",
    "task": "#217_Ajuste Informe Chance-Soporte_Comercial",
    "description": "Despliegue por modalidad y transacciones por código de vendedor.",
    "area": "Mercadeo",
    "requestType": "Tablero",
    "owner": "Maria Nicole Vargas Gonzalez",
    "manager": "Laura Vanessa Toro Escobar",
    "priority": "Media",
    "bucket": "Hecho",
    "rawStatus": "Cerrado",
    "status": "Hecho",
    "progress": 100,
    "dueDate": "2026-09-07 05:00:00",
    "dueState": "No aplica — completada",
    "meetingEligible": false
  },
  {
    "ticket": "218",
    "task": "#218_Validación Informe Ventas por Hora_Soporte_Comercial",
    "description": "Me permito solicitar el ajuste en la información de la regional ya que no me aparece la zona del Diana Turbay.",
    "area": "Comercial",
    "requestType": "Tablero",
    "owner": "Maria Nicole Vargas Gonzalez",
    "manager": "Laura Vanessa Toro Escobar",
    "priority": "Media",
    "bucket": "Hecho",
    "rawStatus": "Cerrado",
    "status": "Hecho",
    "progress": 100,
    "dueDate": "2026-09-07 05:00:00",
    "dueState": "No aplica — completada",
    "meetingEligible": false
  },
  {
    "ticket": "219",
    "task": "#219_Premiacion Pagaencime_Tablero_Comercial",
    "description": "Premiación Pagaencime desde el 1ro de septiembre 2026 por hora",
    "area": "Comercial",
    "requestType": "Tablero",
    "owner": "Maria Nicole Vargas Gonzalez",
    "manager": "Maria Nicole Vargas Gonzalez",
    "priority": "Media",
    "bucket": "Qué hacer",
    "rawStatus": "No iniciada",
    "status": "Pendiente",
    "progress": 0,
    "dueDate": "",
    "dueState": "Sin fecha",
    "meetingEligible": true
  },
  {
    "ticket": "220",
    "task": "#220_Analisis clientes digital_Tablero_Juegos Digitales",
    "description": "Análisis clientes fuera de Bogotá y Cundinamarca canal digital",
    "area": "Juegos Digitales",
    "requestType": "Tablero",
    "owner": "Juan Camilo Potosi Agudelo",
    "manager": "Maria Nicole Vargas Gonzalez",
    "priority": "Media",
    "bucket": "Hecho",
    "rawStatus": "Completado en Planner",
    "status": "Hecho",
    "progress": 100,
    "dueDate": "",
    "dueState": "No aplica — completada",
    "meetingEligible": false
  },
  {
    "ticket": "221",
    "task": "#221_Incluir Pines y recargas_Tablero_Juegos Digitales",
    "description": "Buenos días. Al dashboard existente https://portalanalitica.gelsa.com.co/reports/74, se solicita incluir la participación de Pines y Recargas Digitales, esto con el fin de consultar fácilmente estos productos. Gracias",
    "area": "Gerencia juegos digitales",
    "requestType": "Tablero",
    "owner": "Maria Nicole Vargas Gonzalez",
    "manager": "Maria Nicole Vargas Gonzalez",
    "priority": "Media",
    "bucket": "Hecho",
    "rawStatus": "Cerrado",
    "status": "Hecho",
    "progress": 100,
    "dueDate": "",
    "dueState": "No aplica - completada",
    "meetingEligible": false
  },
  {
    "ticket": "222",
    "task": "#222_Cambio de lider_Tablero_Desarrollo Organizacional",
    "description": "Hola me ayudas cambiándole el líder de la SPT Sur Occidente VD y poniendo a Jairo Giraldo",
    "area": "Desarrollo organizacional",
    "requestType": "Tablero",
    "owner": "Juan David Monroy Machado",
    "manager": "Maria Nicole Vargas Gonzalez",
    "priority": "Media",
    "bucket": "Hecho",
    "rawStatus": "Cerrado",
    "status": "Hecho",
    "progress": 100,
    "dueDate": "",
    "dueState": "No aplica — completada",
    "meetingEligible": false
  },
  {
    "ticket": "223",
    "task": "#223_Permisos Tableros Juegos Digitales_Soporte_Juegos Digitales",
    "description": "Solicito tu colaboración para poder conceder accesos para oscar.sandoval@gelsa.com.co a los siguientes tableros de negocio: https://portalanalitica.gelsa.com.co/reports/179; https://portalanalitica.gelsa.com.co/reports/167; https://portalanalitica.gelsa.com.co/reports/103; https://portalanalitica.gelsa.com.co/reports/107; https://portalanalitica.gelsa.com.co/reports/201",
    "area": "Acceso Reportes Digital",
    "requestType": "Tablero",
    "owner": "Maria Nicole Vargas Gonzalez",
    "manager": "Maria Nicole Vargas Gonzalez",
    "priority": "Media",
    "bucket": "Hecho",
    "rawStatus": "Cerrado",
    "status": "Hecho",
    "progress": 100,
    "dueDate": "46273.20833333333",
    "dueState": "No aplica — completada",
    "meetingEligible": false
  },
  {
    "ticket": "224",
    "task": "#224_Informe Pásarelas_Soporte_Juegos Digitales",
    "description": "Su amable ayuda incluyendo al tablero de pásarelas un filtro por pásarela y validando el de método de pago, aparece Todo Pay duplicado",
    "area": "Juegos Digitales",
    "requestType": "Tablero",
    "owner": "Maria Nicole Vargas Gonzalez",
    "manager": "Maria Nicole Vargas Gonzalez",
    "priority": "Media",
    "bucket": "Hecho",
    "rawStatus": "Cerrado",
    "status": "Hecho",
    "progress": 100,
    "dueDate": "46273.20833333333",
    "dueState": "No aplica — completada",
    "meetingEligible": false
  },
  {
    "ticket": "225",
    "task": "#225_Creacion tablero_Tablero_Activos fijos",
    "description": "Se solicita la creacion de un tablero en donde contenga la informacion de las terminales moviles T2 y Q2 en pdv, tat-vd, backup spt, almacen, datacenter, administrativa, danadas, laboratorio, wpos, de baja, siniestro asi como el paralelo de disponibilidades de un mes a otro. El control de cada una de las referencias de repuestos existentes en almacen generando el semaforo de maximos y minimos, detallando el stock nuevo, reutilizado y los faltantes con sus respectivos valores.",
    "area": "Activos fijos y Almacen",
    "requestType": "Tablero",
    "owner": "Maria Nicole Vargas Gonzalez",
    "manager": "Maria Nicole Vargas Gonzalez",
    "priority": "Media",
    "bucket": "Que hacer",
    "rawStatus": "No iniciada",
    "status": "Pendiente",
    "progress": 0,
    "dueDate": "",
    "dueState": "Sin fecha",
    "meetingEligible": true
  },
  {
    "ticket": "238",
    "task": "#238_Reporte de gestion_Movilidad_Comercial",
    "description": "Se solicita un reporte de la gestión de las visitas de los administradores de la SPT del 11 de agosto.",
    "area": "Comercial",
    "requestType": "Movilidad",
    "owner": "Laura Vanessa Toro Escobar",
    "manager": "Daniela Bermudez Infante",
    "priority": "Media",
    "bucket": "Hecho",
    "rawStatus": "Completado en Planner",
    "status": "Hecho",
    "progress": 100,
    "dueDate": "",
    "dueState": "No aplica — completada",
    "meetingEligible": false
  },
  {
    "ticket": "239",
    "task": "#239_Registro_Movilidad_Comercial",
    "description": "Hola, me ayudan con el registro fotográfico de las visitas del formulario Hoja de vida TAT, principalmente el cod 402880",
    "area": "Comercial",
    "requestType": "Movilidad",
    "owner": "Asignación por validar",
    "manager": "Daniela Bermudez Infante",
    "priority": "Media",
    "bucket": "Haciendo",
    "rawStatus": "Completado en Planner",
    "status": "Hecho",
    "progress": 100,
    "dueDate": "",
    "dueState": "No aplica — completada",
    "meetingEligible": false
  },
  {
    "ticket": "240",
    "task": "#240_Reporte de gestion en campo_Movilidad_Comercial",
    "description": "Cordial saludo. Me permito solicitar el apoyo por parte de la oficina de inteligencia para realizar una validación al detalle de las visitas ejecutadas por parte del administradora Leidy Geraldine Panqueva, dado que al realizar la verificación en el mapa se identifican unas visitas pero al validar las ejecutadas no muestra las líneas rojas, adicional dentro de los informes se identifican largos periodos en puntos o inicio de las rutas tarde, por lo cual me gustaría revisarlo directamente con ustedes para garantizar que el análisis es correcto, para entrar a intervenir al administradora.",
    "area": "Comercial",
    "requestType": "Movilidad",
    "owner": "Laura Vanessa Toro Escobar",
    "manager": "Daniela Bermudez Infante",
    "priority": "Media",
    "bucket": "Hecho",
    "rawStatus": "Completado",
    "status": "Hecho",
    "progress": 100,
    "dueDate": "",
    "dueState": "No aplica — completada",
    "meetingEligible": false
  },
  {
    "ticket": "242",
    "task": "#242_Ajuste Informe por Hora Dirección_Soporte_Comercial",
    "description": "Solicito la revisión del informe por hora de Dirección.",
    "area": "Comercial",
    "requestType": "Tablero",
    "owner": "Juan Camilo Potosi Agudelo",
    "manager": "Maria Nicole Vargas Gonzalez",
    "priority": "Media",
    "bucket": "Haciendo",
    "rawStatus": "Pendiente",
    "status": "En curso",
    "progress": 0,
    "dueDate": "",
    "dueState": "En plazo",
    "meetingEligible": true
  },
  {
    "ticket": "243",
    "task": "#243_Tablero Premiación por Hora_Requerimiento_Comercial",
    "description": "Solicito una herramienta para hacer el seguimiento de la premiación por hora.",
    "area": "Comercial",
    "requestType": "Tablero",
    "owner": "Juan Camilo Potosi Agudelo",
    "manager": "Maria Nicole Vargas Gonzalez",
    "priority": "Media",
    "bucket": "Hecho",
    "rawStatus": "Completado en Planner",
    "status": "Hecho",
    "progress": 100,
    "dueDate": "",
    "dueState": "No aplica — completada",
    "meetingEligible": false
  },
  {
    "ticket": "244",
    "task": "#244_Ajuste Informe Direccion_Soporte_Comercial",
    "description": "En el informe por hora que se envia a la gerencia, dejar la tabla por SPT que se tenia antes en el cuerpo del correo",
    "area": "Comercial",
    "requestType": "Tablero",
    "owner": "Maria Nicole Vargas Gonzalez",
    "manager": "Maria Nicole Vargas Gonzalez",
    "priority": "Media",
    "bucket": "Hecho",
    "rawStatus": "Cerrado",
    "status": "Hecho",
    "progress": 100,
    "dueDate": "46281.208333333336",
    "dueState": "No aplica - completada",
    "meetingEligible": false
  },
  {
    "ticket": "245",
    "task": "#245_Actualizacion tablero_Tablero_Movilidad",
    "description": "Solicito amablemente actualizar las vistas del tablero acompañamiento colocadoras, para sorteo express, Bre-b y BEPS.",
    "area": "Movilidad",
    "requestType": "Tablero",
    "owner": "Juan Camilo Potosi Agudelo",
    "manager": "Maria Nicole Vargas Gonzalez",
    "priority": "Media",
    "bucket": "Qué hacer",
    "rawStatus": "Pendiente",
    "status": "Pendiente",
    "progress": 0,
    "dueDate": "",
    "dueState": "En plazo",
    "meetingEligible": true
  },
  {
    "ticket": "246",
    "task": "#246_Informe Ventas por Municipio y Localidad Agosto_Requerimiento_Comercial",
    "description": "Informe Ventas por Municipio Loterías",
    "area": "Comercial",
    "requestType": "Tablero",
    "owner": "Maria Nicole Vargas Gonzalez",
    "manager": "Maria Nicole Vargas Gonzalez",
    "priority": "Media",
    "bucket": "Hecho",
    "rawStatus": "Completado en Planner",
    "status": "Hecho",
    "progress": 100,
    "dueDate": "",
    "dueState": "No aplica — completada",
    "meetingEligible": false
  },
  {
    "ticket": "247",
    "task": "#247_Reporte gestion en lugar_Movilidad_Comercial",
    "description": "Se requiere el reporte de la gestion en el lugar, de la administradora Liana Villalba.",
    "area": "Comercial",
    "requestType": "Movilidad",
    "owner": "Pendiente por asignar",
    "manager": "Daniela Bermudez Infante",
    "priority": "Media",
    "bucket": "Que hacer",
    "rawStatus": "Pendiente",
    "status": "Pendiente",
    "progress": 0,
    "dueDate": "",
    "dueState": "Sin fecha",
    "meetingEligible": true
  },
  {
    "ticket": "247",
    "task": "#247_Reporte gestion en lugar_Movilidad_Comercial",
    "description": "Se requiere el reporte de la gestion en el lugar, de la administradora Liana Villalba.",
    "area": "Comercial",
    "requestType": "Movilidad",
    "owner": "Pendiente por asignar",
    "manager": "Daniela Bermudez Infante",
    "priority": "Media",
    "bucket": "Que hacer",
    "rawStatus": "Pendiente",
    "status": "Pendiente",
    "progress": 0,
    "dueDate": "",
    "dueState": "Sin fecha",
    "meetingEligible": true
  },
  {
    "ticket": "247",
    "task": "#247_Reporte gestion en lugar_Movilidad_Comercial",
    "description": "Se requiere el reporte de la gestion en el lugar, de la administradora Liana Villalba.",
    "area": "Comercial",
    "requestType": "Movilidad",
    "owner": "Pendiente por asignar",
    "manager": "Daniela Bermudez Infante",
    "priority": "Media",
    "bucket": "Que hacer",
    "rawStatus": "Pendiente",
    "status": "Pendiente",
    "progress": 0,
    "dueDate": "",
    "dueState": "Sin fecha",
    "meetingEligible": true
  },
  {
    "ticket": "247",
    "task": "#247_Reporte gestion en lugar_Movilidad_Comercial",
    "description": "Se requiere el reporte de la gestion en el lugar, de la administradora Liana Villalba.",
    "area": "Comercial",
    "requestType": "Movilidad",
    "owner": "Pendiente por asignar",
    "manager": "Daniela Bermudez Infante",
    "priority": "Media",
    "bucket": "Que hacer",
    "rawStatus": "Pendiente",
    "status": "Pendiente",
    "progress": 0,
    "dueDate": "",
    "dueState": "Sin fecha",
    "meetingEligible": true
  },
  {
    "ticket": "247",
    "task": "#247_Reporte gestion en lugar_Movilidad_Comercial",
    "description": "Se requiere el reporte de la gestion en el lugar, de la administradora Liana Villalba.",
    "area": "Comercial",
    "requestType": "Movilidad",
    "owner": "Pendiente por asignar",
    "manager": "Daniela Bermudez Infante",
    "priority": "Media",
    "bucket": "Que hacer",
    "rawStatus": "Pendiente",
    "status": "Pendiente",
    "progress": 0,
    "dueDate": "",
    "dueState": "Sin fecha",
    "meetingEligible": true
  },
  {
    "ticket": "247",
    "task": "#247_Reporte gestion en lugar_Movilidad_Comercial",
    "description": "Se requiere el reporte de la gestion en el lugar, de la administradora Liana Villalba.",
    "area": "Comercial",
    "requestType": "Movilidad",
    "owner": "Pendiente por asignar",
    "manager": "Daniela Bermudez Infante",
    "priority": "Media",
    "bucket": "Que hacer",
    "rawStatus": "Pendiente",
    "status": "Pendiente",
    "progress": 0,
    "dueDate": "",
    "dueState": "Sin fecha",
    "meetingEligible": true
  },
  {
    "ticket": "247",
    "task": "#247_Reporte gestion en lugar_Movilidad_Comercial",
    "description": "Se requiere el reporte de la gestion en el lugar, de la administradora Liana Villalba.",
    "area": "Comercial",
    "requestType": "Movilidad",
    "owner": "Pendiente por asignar",
    "manager": "Daniela Bermudez Infante",
    "priority": "Media",
    "bucket": "Que hacer",
    "rawStatus": "Pendiente",
    "status": "Pendiente",
    "progress": 0,
    "dueDate": "",
    "dueState": "Sin fecha",
    "meetingEligible": true
  },
  {
    "ticket": "247",
    "task": "#247_Reporte gestion en lugar_Movilidad_Comercial",
    "description": "Se requiere el reporte de la gestion en el lugar, de la administradora Liana Villalba.",
    "area": "Comercial",
    "requestType": "Movilidad",
    "owner": "Pendiente por asignar",
    "manager": "Daniela Bermudez Infante",
    "priority": "Media",
    "bucket": "Que hacer",
    "rawStatus": "Pendiente",
    "status": "Pendiente",
    "progress": 0,
    "dueDate": "",
    "dueState": "Sin fecha",
    "meetingEligible": true
  },
  {
    "ticket": "247",
    "task": "#247_Reporte gestion en lugar_Movilidad_Comercial",
    "description": "Se requiere el reporte de la gestion en el lugar, de la administradora Liana Villalba.",
    "area": "Comercial",
    "requestType": "Movilidad",
    "owner": "Pendiente por asignar",
    "manager": "Daniela Bermudez Infante",
    "priority": "Media",
    "bucket": "Que hacer",
    "rawStatus": "Pendiente",
    "status": "Pendiente",
    "progress": 0,
    "dueDate": "",
    "dueState": "Sin fecha",
    "meetingEligible": true
  },
  {
    "ticket": "247",
    "task": "#247_Reporte gestion en lugar_Movilidad_Comercial",
    "description": "Se requiere el reporte de la gestion en el lugar, de la administradora Liana Villalba.",
    "area": "Comercial",
    "requestType": "Movilidad",
    "owner": "Pendiente por asignar",
    "manager": "Daniela Bermudez Infante",
    "priority": "Media",
    "bucket": "Que hacer",
    "rawStatus": "Pendiente",
    "status": "Pendiente",
    "progress": 0,
    "dueDate": "",
    "dueState": "Sin fecha",
    "meetingEligible": true
  },
  {
    "ticket": "247",
    "task": "#247_Reporte gestion en lugar_Movilidad_Comercial",
    "description": "Se requiere el reporte de la gestion en el lugar, de la administradora Liana Villalba.",
    "area": "Comercial",
    "requestType": "Movilidad",
    "owner": "Pendiente por asignar",
    "manager": "Daniela Bermudez Infante",
    "priority": "Media",
    "bucket": "Que hacer",
    "rawStatus": "Pendiente",
    "status": "Pendiente",
    "progress": 0,
    "dueDate": "",
    "dueState": "Sin fecha",
    "meetingEligible": true
  },
  {
    "ticket": "247",
    "task": "#247_Reporte gestion en lugar_Movilidad_Comercial",
    "description": "Se requiere el reporte de la gestion en el lugar, de la administradora Liana Villalba.",
    "area": "Comercial",
    "requestType": "Movilidad",
    "owner": "Pendiente por asignar",
    "manager": "Daniela Bermudez Infante",
    "priority": "Media",
    "bucket": "Que hacer",
    "rawStatus": "Pendiente",
    "status": "Pendiente",
    "progress": 0,
    "dueDate": "",
    "dueState": "Sin fecha",
    "meetingEligible": true
  },
  {
    "ticket": "247",
    "task": "#247_Reporte gestion en lugar_Movilidad_Comercial",
    "description": "Se requiere el reporte de la gestion en el lugar, de la administradora Liana Villalba.",
    "area": "Comercial",
    "requestType": "Movilidad",
    "owner": "Pendiente por asignar",
    "manager": "Daniela Bermudez Infante",
    "priority": "Media",
    "bucket": "Que hacer",
    "rawStatus": "Pendiente",
    "status": "Pendiente",
    "progress": 0,
    "dueDate": "",
    "dueState": "Sin fecha",
    "meetingEligible": true
  },
  {
    "ticket": "247",
    "task": "#247_Reporte gestion en lugar_Movilidad_Comercial",
    "description": "Se requiere el reporte de la gestion en el lugar, de la administradora Liana Villalba.",
    "area": "Comercial",
    "requestType": "Movilidad",
    "owner": "Pendiente por asignar",
    "manager": "Daniela Bermudez Infante",
    "priority": "Media",
    "bucket": "Que hacer",
    "rawStatus": "Pendiente",
    "status": "Pendiente",
    "progress": 0,
    "dueDate": "",
    "dueState": "Sin fecha",
    "meetingEligible": true
  },
  {
    "ticket": "247",
    "task": "#247_Reporte gestion en lugar_Movilidad_Comercial",
    "description": "Se requiere el reporte de la gestion en el lugar, de la administradora Liana Villalba.",
    "area": "Comercial",
    "requestType": "Movilidad",
    "owner": "Pendiente por asignar",
    "manager": "Daniela Bermudez Infante",
    "priority": "Media",
    "bucket": "Que hacer",
    "rawStatus": "Pendiente",
    "status": "Pendiente",
    "progress": 0,
    "dueDate": "",
    "dueState": "Sin fecha",
    "meetingEligible": true
  },
  {
    "ticket": "247",
    "task": "#247_Reporte gestion en lugar_Movilidad_Comercial",
    "description": "Se requiere el reporte de la gestion en el lugar, de la administradora Liana Villalba.",
    "area": "Comercial",
    "requestType": "Movilidad",
    "owner": "Pendiente por asignar",
    "manager": "Daniela Bermudez Infante",
    "priority": "Media",
    "bucket": "Que hacer",
    "rawStatus": "Pendiente",
    "status": "Pendiente",
    "progress": 0,
    "dueDate": "",
    "dueState": "Sin fecha",
    "meetingEligible": true
  },
  {
    "ticket": "247",
    "task": "#247_Reporte gestion en lugar_Movilidad_Comercial",
    "description": "Se requiere el reporte de la gestion en el lugar, de la administradora Liana Villalba.",
    "area": "Comercial",
    "requestType": "Movilidad",
    "owner": "Pendiente por asignar",
    "manager": "Daniela Bermudez Infante",
    "priority": "Media",
    "bucket": "Que hacer",
    "rawStatus": "Pendiente",
    "status": "Pendiente",
    "progress": 0,
    "dueDate": "",
    "dueState": "Sin fecha",
    "meetingEligible": true
  },
  {
    "ticket": "247",
    "task": "#247_Reporte gestion en lugar_Movilidad_Comercial",
    "description": "Se requiere el reporte de la gestion en el lugar, de la administradora Liana Villalba.",
    "area": "Comercial",
    "requestType": "Movilidad",
    "owner": "Pendiente por asignar",
    "manager": "Daniela Bermudez Infante",
    "priority": "Media",
    "bucket": "Que hacer",
    "rawStatus": "Pendiente",
    "status": "Pendiente",
    "progress": 0,
    "dueDate": "",
    "dueState": "Sin fecha",
    "meetingEligible": true
  },
  {
    "ticket": "247",
    "task": "#247_Reporte gestion en lugar_Movilidad_Comercial",
    "description": "Se requiere el reporte de la gestion en el lugar, de la administradora Liana Villalba.",
    "area": "Comercial",
    "requestType": "Movilidad",
    "owner": "Pendiente por asignar",
    "manager": "Daniela Bermudez Infante",
    "priority": "Media",
    "bucket": "Que hacer",
    "rawStatus": "Pendiente",
    "status": "Pendiente",
    "progress": 0,
    "dueDate": "",
    "dueState": "Sin fecha",
    "meetingEligible": true
  },
  {
    "ticket": "247",
    "task": "#247_Reporte gestion en lugar_Movilidad_Comercial",
    "description": "Se requiere el reporte de la gestion en el lugar, de la administradora Liana Villalba.",
    "area": "Comercial",
    "requestType": "Movilidad",
    "owner": "Pendiente por asignar",
    "manager": "Daniela Bermudez Infante",
    "priority": "Media",
    "bucket": "Que hacer",
    "rawStatus": "Pendiente",
    "status": "Pendiente",
    "progress": 0,
    "dueDate": "",
    "dueState": "Sin fecha",
    "meetingEligible": true
  },
  {
    "ticket": "247",
    "task": "#247_Reporte gestion en lugar_Movilidad_Comercial",
    "description": "Se requiere el reporte de la gestion en el lugar, de la administradora Liana Villalba.",
    "area": "Comercial",
    "requestType": "Movilidad",
    "owner": "Pendiente por asignar",
    "manager": "Daniela Bermudez Infante",
    "priority": "Media",
    "bucket": "Que hacer",
    "rawStatus": "Pendiente",
    "status": "Pendiente",
    "progress": 0,
    "dueDate": "",
    "dueState": "Sin fecha",
    "meetingEligible": true
  },
  {
    "ticket": "247",
    "task": "#247_Reporte gestion en lugar_Movilidad_Comercial",
    "description": "Se requiere el reporte de la gestion en el lugar, de la administradora Liana Villalba.",
    "area": "Comercial",
    "requestType": "Movilidad",
    "owner": "Pendiente por asignar",
    "manager": "Daniela Bermudez Infante",
    "priority": "Media",
    "bucket": "Que hacer",
    "rawStatus": "Pendiente",
    "status": "Pendiente",
    "progress": 0,
    "dueDate": "",
    "dueState": "Sin fecha",
    "meetingEligible": true
  },
  {
    "ticket": "99",
    "task": "Ticket #99 · cierre confirmado manualmente",
    "description": "Cierre confirmado por actualización manual; pendiente asociación cuando aparezca en el próximo Excel.",
    "area": "Actualización manual",
    "requestType": "",
    "owner": "Pendiente por asociar",
    "manager": "",
    "priority": "",
    "bucket": "Hecho",
    "rawStatus": "Completado",
    "status": "Hecho",
    "progress": 100,
    "dueDate": "",
    "dueState": "No aplica — completada",
    "meetingEligible": false
  },
  {
    "ticket": "269",
    "task": "Ticket #269 · cierre confirmado manualmente",
    "description": "Cierre confirmado por actualización manual; pendiente asociación cuando aparezca en el próximo Excel.",
    "area": "Actualización manual",
    "requestType": "",
    "owner": "Pendiente por asociar",
    "manager": "",
    "priority": "",
    "bucket": "Hecho",
    "rawStatus": "Completado",
    "status": "Hecho",
    "progress": 100,
    "dueDate": "",
    "dueState": "No aplica — completada",
    "meetingEligible": false
  },
  {
    "ticket": "271",
    "task": "Ticket #271 · cierre confirmado manualmente",
    "description": "Cierre confirmado por actualización manual; pendiente asociación cuando aparezca en el próximo Excel.",
    "area": "Actualización manual",
    "requestType": "",
    "owner": "Pendiente por asociar",
    "manager": "",
    "priority": "",
    "bucket": "Hecho",
    "rawStatus": "Completado",
    "status": "Hecho",
    "progress": 100,
    "dueDate": "",
    "dueState": "No aplica — completada",
    "meetingEligible": false
  },
  {
    "ticket": "272",
    "task": "Ticket #272 · cierre confirmado manualmente",
    "description": "Cierre confirmado por actualización manual; pendiente asociación cuando aparezca en el próximo Excel.",
    "area": "Actualización manual",
    "requestType": "",
    "owner": "Pendiente por asociar",
    "manager": "",
    "priority": "",
    "bucket": "Hecho",
    "rawStatus": "Completado",
    "status": "Hecho",
    "progress": 100,
    "dueDate": "",
    "dueState": "No aplica — completada",
    "meetingEligible": false
  },
  {
    "ticket": "274",
    "task": "Ticket #274 · cierre confirmado manualmente",
    "description": "Cierre confirmado por actualización manual; pendiente asociación cuando aparezca en el próximo Excel.",
    "area": "Actualización manual",
    "requestType": "",
    "owner": "Pendiente por asociar",
    "manager": "",
    "priority": "",
    "bucket": "Hecho",
    "rawStatus": "Completado",
    "status": "Hecho",
    "progress": 100,
    "dueDate": "",
    "dueState": "No aplica — completada",
    "meetingEligible": false
  },
  {
    "ticket": "275",
    "task": "Ticket #275 · cierre confirmado manualmente",
    "description": "Cierre confirmado por actualización manual; pendiente asociación cuando aparezca en el próximo Excel.",
    "area": "Actualización manual",
    "requestType": "",
    "owner": "Pendiente por asociar",
    "manager": "",
    "priority": "",
    "bucket": "Hecho",
    "rawStatus": "Completado",
    "status": "Hecho",
    "progress": 100,
    "dueDate": "",
    "dueState": "No aplica — completada",
    "meetingEligible": false
  }
];
